development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: test-products_development
  pool:     5
  username: alex
  password: alex
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: test-products_test
  pool:     5
  username: alex
  password: alex
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: test-products_production
  pool:     5
  username: alex
  password: alex
  template: template0
